### ISSUE TITLE
Metadata.yaml SHA is a commit behind the latest template.tpl

### ISSUE THREAD

**Issue by jonathanleekay2** [mbaersch/scoby-tag-server#1]
Hi,

Thank you for submitting your template for a Community Template Gallery review. I noticed that the SHA in metadata.yaml[0] is a commit behind the latest version of template.tpl. If you want to use the latest version of template.tpl for the Template Gallery then you'll have to update that SHA[1].

Please let me know if you have any questions.

Thanks
Jon

[0] https://github.com/mbaersch/scoby-tag-server/blob/060c9e8595dc36d34a04dc1798277b7c9b17d30f/metadata.yaml#L5
[1] https://developers.google.com/tag-platform/tag-manager/templates/gallery#metadatayaml

**Comment by mbaersch** [comment]
Hi Jon,

thanks for letting me know! Just updated the SHA value.
